import { Inter } from "next/font/google";
import "./globals.css";
import { redirect } from "next/dist/server/api-utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>{/* Add any metadata here if needed */}</head>
      <body className={inter.className}>
        <header style={{ backgroundColor: "red" }} className="bg-red-200">
          This is my header
        </header>
        {children}
        <footer className="bg-black text-white">This is my footer</footer>
      </body>
    </html>
  );
}
